name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Allow other versions to continue even if one fails
      fail-fast: false
      matrix:
        python-version: [3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Explicitly install development tools
        python -m pip install flake8 pytest pytest-cov
        # Then install the package with dev extras
        python -m pip install -e ".[dev]" -v
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # Type checking temporarily disabled
    # - name: Type check with mypy
    #  run: |
    #    mypy src
    - name: Test with pytest
      run: |
        pytest tests/
        # Run with coverage report generation only if explicitly requested
        # pytest --cov=mindchain --cov-report=xml tests/
    
    # Codecov upload temporarily disabled
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./coverage.xml
    #     fail_ci_if_error: false  # Don't fail the build if codecov upload fails
